language: node_js

node_js:
  - 0.12

# Faster builds on container infrastructure
sudo: false

notifications:
  email:
    recipients:
      - ilanguagelab-dev@googlegroups.com
    on_success: change
    on_failure: always

before_install:
  # Download and configure deps
  - npm install -g gulp 
  - npm install -g jasmine-node 
  # npm install -g git://github.com/kacperus/jasmine-node.git &&

script: gulp
